/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithdrawRouteImport } from './routes/withdraw'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as SpinRouteImport } from './routes/spin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GamesRouteImport } from './routes/games'
import { Route as DepositRouteImport } from './routes/deposit'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WithdrawIndexRouteImport } from './routes/withdraw.index'
import { Route as GamesIndexRouteImport } from './routes/games.index'
import { Route as DepositIndexRouteImport } from './routes/deposit.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as WithdrawUsdtRouteImport } from './routes/withdraw.usdt'
import { Route as WithdrawBankRouteImport } from './routes/withdraw.bank'
import { Route as GamesSlotMachineRouteImport } from './routes/games.slot-machine'
import { Route as GamesLuckyBoxRouteImport } from './routes/games.lucky-box'
import { Route as GamesLuckWheelRouteImport } from './routes/games.luck-wheel'
import { Route as GamesBonusDropRouteImport } from './routes/games.bonus-drop'
import { Route as DepositUsdtRouteImport } from './routes/deposit.usdt'
import { Route as DepositPendingRouteImport } from './routes/deposit.pending'
import { Route as DepositGiftCardRouteImport } from './routes/deposit.gift-card'
import { Route as DepositBankRouteImport } from './routes/deposit.bank'
import { Route as AdminWithdrawalsRouteImport } from './routes/admin.withdrawals'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSpinRouteImport } from './routes/admin.spin'
import { Route as AdminOffersRouteImport } from './routes/admin.offers'
import { Route as AdminDepositsRouteImport } from './routes/admin.deposits'

const WithdrawRoute = WithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const SpinRoute = SpinRouteImport.update({
  id: '/spin',
  path: '/spin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositRoute = DepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WithdrawIndexRoute = WithdrawIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WithdrawRoute,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GamesRoute,
} as any)
const DepositIndexRoute = DepositIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DepositRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const WithdrawUsdtRoute = WithdrawUsdtRouteImport.update({
  id: '/usdt',
  path: '/usdt',
  getParentRoute: () => WithdrawRoute,
} as any)
const WithdrawBankRoute = WithdrawBankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => WithdrawRoute,
} as any)
const GamesSlotMachineRoute = GamesSlotMachineRouteImport.update({
  id: '/slot-machine',
  path: '/slot-machine',
  getParentRoute: () => GamesRoute,
} as any)
const GamesLuckyBoxRoute = GamesLuckyBoxRouteImport.update({
  id: '/lucky-box',
  path: '/lucky-box',
  getParentRoute: () => GamesRoute,
} as any)
const GamesLuckWheelRoute = GamesLuckWheelRouteImport.update({
  id: '/luck-wheel',
  path: '/luck-wheel',
  getParentRoute: () => GamesRoute,
} as any)
const GamesBonusDropRoute = GamesBonusDropRouteImport.update({
  id: '/bonus-drop',
  path: '/bonus-drop',
  getParentRoute: () => GamesRoute,
} as any)
const DepositUsdtRoute = DepositUsdtRouteImport.update({
  id: '/usdt',
  path: '/usdt',
  getParentRoute: () => DepositRoute,
} as any)
const DepositPendingRoute = DepositPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => DepositRoute,
} as any)
const DepositGiftCardRoute = DepositGiftCardRouteImport.update({
  id: '/gift-card',
  path: '/gift-card',
  getParentRoute: () => DepositRoute,
} as any)
const DepositBankRoute = DepositBankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => DepositRoute,
} as any)
const AdminWithdrawalsRoute = AdminWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSpinRoute = AdminSpinRouteImport.update({
  id: '/spin',
  path: '/spin',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOffersRoute = AdminOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDepositsRoute = AdminDepositsRouteImport.update({
  id: '/deposits',
  path: '/deposits',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/deposit': typeof DepositRouteWithChildren
  '/games': typeof GamesRouteWithChildren
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/spin': typeof SpinRoute
  '/wallet': typeof WalletRoute
  '/withdraw': typeof WithdrawRouteWithChildren
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/spin': typeof AdminSpinRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/deposit/bank': typeof DepositBankRoute
  '/deposit/gift-card': typeof DepositGiftCardRoute
  '/deposit/pending': typeof DepositPendingRoute
  '/deposit/usdt': typeof DepositUsdtRoute
  '/games/bonus-drop': typeof GamesBonusDropRoute
  '/games/luck-wheel': typeof GamesLuckWheelRoute
  '/games/lucky-box': typeof GamesLuckyBoxRoute
  '/games/slot-machine': typeof GamesSlotMachineRoute
  '/withdraw/bank': typeof WithdrawBankRoute
  '/withdraw/usdt': typeof WithdrawUsdtRoute
  '/admin/': typeof AdminIndexRoute
  '/deposit/': typeof DepositIndexRoute
  '/games/': typeof GamesIndexRoute
  '/withdraw/': typeof WithdrawIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/spin': typeof SpinRoute
  '/wallet': typeof WalletRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/spin': typeof AdminSpinRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/deposit/bank': typeof DepositBankRoute
  '/deposit/gift-card': typeof DepositGiftCardRoute
  '/deposit/pending': typeof DepositPendingRoute
  '/deposit/usdt': typeof DepositUsdtRoute
  '/games/bonus-drop': typeof GamesBonusDropRoute
  '/games/luck-wheel': typeof GamesLuckWheelRoute
  '/games/lucky-box': typeof GamesLuckyBoxRoute
  '/games/slot-machine': typeof GamesSlotMachineRoute
  '/withdraw/bank': typeof WithdrawBankRoute
  '/withdraw/usdt': typeof WithdrawUsdtRoute
  '/admin': typeof AdminIndexRoute
  '/deposit': typeof DepositIndexRoute
  '/games': typeof GamesIndexRoute
  '/withdraw': typeof WithdrawIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/deposit': typeof DepositRouteWithChildren
  '/games': typeof GamesRouteWithChildren
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/spin': typeof SpinRoute
  '/wallet': typeof WalletRoute
  '/withdraw': typeof WithdrawRouteWithChildren
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/spin': typeof AdminSpinRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/deposit/bank': typeof DepositBankRoute
  '/deposit/gift-card': typeof DepositGiftCardRoute
  '/deposit/pending': typeof DepositPendingRoute
  '/deposit/usdt': typeof DepositUsdtRoute
  '/games/bonus-drop': typeof GamesBonusDropRoute
  '/games/luck-wheel': typeof GamesLuckWheelRoute
  '/games/lucky-box': typeof GamesLuckyBoxRoute
  '/games/slot-machine': typeof GamesSlotMachineRoute
  '/withdraw/bank': typeof WithdrawBankRoute
  '/withdraw/usdt': typeof WithdrawUsdtRoute
  '/admin/': typeof AdminIndexRoute
  '/deposit/': typeof DepositIndexRoute
  '/games/': typeof GamesIndexRoute
  '/withdraw/': typeof WithdrawIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/deposit'
    | '/games'
    | '/login'
    | '/offers'
    | '/profile'
    | '/signup'
    | '/spin'
    | '/wallet'
    | '/withdraw'
    | '/admin/deposits'
    | '/admin/offers'
    | '/admin/spin'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/deposit/bank'
    | '/deposit/gift-card'
    | '/deposit/pending'
    | '/deposit/usdt'
    | '/games/bonus-drop'
    | '/games/luck-wheel'
    | '/games/lucky-box'
    | '/games/slot-machine'
    | '/withdraw/bank'
    | '/withdraw/usdt'
    | '/admin/'
    | '/deposit/'
    | '/games/'
    | '/withdraw/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/offers'
    | '/profile'
    | '/signup'
    | '/spin'
    | '/wallet'
    | '/admin/deposits'
    | '/admin/offers'
    | '/admin/spin'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/deposit/bank'
    | '/deposit/gift-card'
    | '/deposit/pending'
    | '/deposit/usdt'
    | '/games/bonus-drop'
    | '/games/luck-wheel'
    | '/games/lucky-box'
    | '/games/slot-machine'
    | '/withdraw/bank'
    | '/withdraw/usdt'
    | '/admin'
    | '/deposit'
    | '/games'
    | '/withdraw'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/deposit'
    | '/games'
    | '/login'
    | '/offers'
    | '/profile'
    | '/signup'
    | '/spin'
    | '/wallet'
    | '/withdraw'
    | '/admin/deposits'
    | '/admin/offers'
    | '/admin/spin'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/deposit/bank'
    | '/deposit/gift-card'
    | '/deposit/pending'
    | '/deposit/usdt'
    | '/games/bonus-drop'
    | '/games/luck-wheel'
    | '/games/lucky-box'
    | '/games/slot-machine'
    | '/withdraw/bank'
    | '/withdraw/usdt'
    | '/admin/'
    | '/deposit/'
    | '/games/'
    | '/withdraw/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DepositRoute: typeof DepositRouteWithChildren
  GamesRoute: typeof GamesRouteWithChildren
  LoginRoute: typeof LoginRoute
  OffersRoute: typeof OffersRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  SpinRoute: typeof SpinRoute
  WalletRoute: typeof WalletRoute
  WithdrawRoute: typeof WithdrawRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/withdraw': {
      id: '/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof WithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spin': {
      id: '/spin'
      path: '/spin'
      fullPath: '/spin'
      preLoaderRoute: typeof SpinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposit': {
      id: '/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof DepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/withdraw/': {
      id: '/withdraw/'
      path: '/'
      fullPath: '/withdraw/'
      preLoaderRoute: typeof WithdrawIndexRouteImport
      parentRoute: typeof WithdrawRoute
    }
    '/games/': {
      id: '/games/'
      path: '/'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof GamesRoute
    }
    '/deposit/': {
      id: '/deposit/'
      path: '/'
      fullPath: '/deposit/'
      preLoaderRoute: typeof DepositIndexRouteImport
      parentRoute: typeof DepositRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/withdraw/usdt': {
      id: '/withdraw/usdt'
      path: '/usdt'
      fullPath: '/withdraw/usdt'
      preLoaderRoute: typeof WithdrawUsdtRouteImport
      parentRoute: typeof WithdrawRoute
    }
    '/withdraw/bank': {
      id: '/withdraw/bank'
      path: '/bank'
      fullPath: '/withdraw/bank'
      preLoaderRoute: typeof WithdrawBankRouteImport
      parentRoute: typeof WithdrawRoute
    }
    '/games/slot-machine': {
      id: '/games/slot-machine'
      path: '/slot-machine'
      fullPath: '/games/slot-machine'
      preLoaderRoute: typeof GamesSlotMachineRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/lucky-box': {
      id: '/games/lucky-box'
      path: '/lucky-box'
      fullPath: '/games/lucky-box'
      preLoaderRoute: typeof GamesLuckyBoxRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/luck-wheel': {
      id: '/games/luck-wheel'
      path: '/luck-wheel'
      fullPath: '/games/luck-wheel'
      preLoaderRoute: typeof GamesLuckWheelRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/bonus-drop': {
      id: '/games/bonus-drop'
      path: '/bonus-drop'
      fullPath: '/games/bonus-drop'
      preLoaderRoute: typeof GamesBonusDropRouteImport
      parentRoute: typeof GamesRoute
    }
    '/deposit/usdt': {
      id: '/deposit/usdt'
      path: '/usdt'
      fullPath: '/deposit/usdt'
      preLoaderRoute: typeof DepositUsdtRouteImport
      parentRoute: typeof DepositRoute
    }
    '/deposit/pending': {
      id: '/deposit/pending'
      path: '/pending'
      fullPath: '/deposit/pending'
      preLoaderRoute: typeof DepositPendingRouteImport
      parentRoute: typeof DepositRoute
    }
    '/deposit/gift-card': {
      id: '/deposit/gift-card'
      path: '/gift-card'
      fullPath: '/deposit/gift-card'
      preLoaderRoute: typeof DepositGiftCardRouteImport
      parentRoute: typeof DepositRoute
    }
    '/deposit/bank': {
      id: '/deposit/bank'
      path: '/bank'
      fullPath: '/deposit/bank'
      preLoaderRoute: typeof DepositBankRouteImport
      parentRoute: typeof DepositRoute
    }
    '/admin/withdrawals': {
      id: '/admin/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AdminWithdrawalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/spin': {
      id: '/admin/spin'
      path: '/spin'
      fullPath: '/admin/spin'
      preLoaderRoute: typeof AdminSpinRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/offers': {
      id: '/admin/offers'
      path: '/offers'
      fullPath: '/admin/offers'
      preLoaderRoute: typeof AdminOffersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/deposits': {
      id: '/admin/deposits'
      path: '/deposits'
      fullPath: '/admin/deposits'
      preLoaderRoute: typeof AdminDepositsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDepositsRoute: typeof AdminDepositsRoute
  AdminOffersRoute: typeof AdminOffersRoute
  AdminSpinRoute: typeof AdminSpinRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWithdrawalsRoute: typeof AdminWithdrawalsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDepositsRoute: AdminDepositsRoute,
  AdminOffersRoute: AdminOffersRoute,
  AdminSpinRoute: AdminSpinRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWithdrawalsRoute: AdminWithdrawalsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DepositRouteChildren {
  DepositBankRoute: typeof DepositBankRoute
  DepositGiftCardRoute: typeof DepositGiftCardRoute
  DepositPendingRoute: typeof DepositPendingRoute
  DepositUsdtRoute: typeof DepositUsdtRoute
  DepositIndexRoute: typeof DepositIndexRoute
}

const DepositRouteChildren: DepositRouteChildren = {
  DepositBankRoute: DepositBankRoute,
  DepositGiftCardRoute: DepositGiftCardRoute,
  DepositPendingRoute: DepositPendingRoute,
  DepositUsdtRoute: DepositUsdtRoute,
  DepositIndexRoute: DepositIndexRoute,
}

const DepositRouteWithChildren =
  DepositRoute._addFileChildren(DepositRouteChildren)

interface GamesRouteChildren {
  GamesBonusDropRoute: typeof GamesBonusDropRoute
  GamesLuckWheelRoute: typeof GamesLuckWheelRoute
  GamesLuckyBoxRoute: typeof GamesLuckyBoxRoute
  GamesSlotMachineRoute: typeof GamesSlotMachineRoute
  GamesIndexRoute: typeof GamesIndexRoute
}

const GamesRouteChildren: GamesRouteChildren = {
  GamesBonusDropRoute: GamesBonusDropRoute,
  GamesLuckWheelRoute: GamesLuckWheelRoute,
  GamesLuckyBoxRoute: GamesLuckyBoxRoute,
  GamesSlotMachineRoute: GamesSlotMachineRoute,
  GamesIndexRoute: GamesIndexRoute,
}

const GamesRouteWithChildren = GamesRoute._addFileChildren(GamesRouteChildren)

interface WithdrawRouteChildren {
  WithdrawBankRoute: typeof WithdrawBankRoute
  WithdrawUsdtRoute: typeof WithdrawUsdtRoute
  WithdrawIndexRoute: typeof WithdrawIndexRoute
}

const WithdrawRouteChildren: WithdrawRouteChildren = {
  WithdrawBankRoute: WithdrawBankRoute,
  WithdrawUsdtRoute: WithdrawUsdtRoute,
  WithdrawIndexRoute: WithdrawIndexRoute,
}

const WithdrawRouteWithChildren = WithdrawRoute._addFileChildren(
  WithdrawRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DepositRoute: DepositRouteWithChildren,
  GamesRoute: GamesRouteWithChildren,
  LoginRoute: LoginRoute,
  OffersRoute: OffersRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  SpinRoute: SpinRoute,
  WalletRoute: WalletRoute,
  WithdrawRoute: WithdrawRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
